logging.level:
  org.springframework.security: TRACE

spring:
  security:
    saml2:
      relyingparty:
        registration:
          liferay:
            signing.credentials:
              - private-key-location: classpath:credentials/liferay.key
                certificate-location: classpath:credentials/liferay.crt
            singlelogout:
              binding: POST
              url: "{baseUrl}/logout/saml2/slo"
            assertingparty.metadata-uri: http://idptest.com:8180/c/portal/saml/metadata
